  - title: Mobile Development
    description: "App design, cross-platform development, and mobile testing to enhance your Mobile Development offerings"
    service-1: "UI/UX Design"
    service-2: "Native Android App"
    service-3: "Cross-Platform App"
  - title: Web Development
    description: "Key learning areas: Programming languages, Scripting Languages, Web Development, Databases."
    service-1: "UI/UX Design"
    service-2: "WordPress Website"
    service-3: "React/Next.js Website"